# Generated by Django 3.2.9 on 2021-11-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProudctImage',
            new_name='ProductImage',
        ),
    ]
